services:
    caddy:
        image: caddy:2.11.6-alpine
        ports:
            - "5000:5000"
            - "5001:5001"
        volumes:
            - ./docker/development/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./docker/development/caddy/users:/etc/caddy-auth/users:ro
        depends_on:
            - registry
            - cache-registry

    registry:
        image: registry:3.1.1
        volumes:
            - registry:/var/lib/registry

    cache-registry:
        image: registry:3.1.1
        restart: always
        environment:
            REGISTRY_LOG_LEVEL: info
            REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
            REGISTRY_PROXY_TTL: 168h
            REGISTRY_STORAGE_DELETE_ENABLED: "true"
        volumes:
            - cache-registry:/var/lib/registry

volumes:
    registry:
    cache-registry:
